export const Routes = {
	Main: "/",
	Auth: {
		SignUp: "/auth/sign-up",
		SignIn: "/auth/sign-in",
		ForgotPassword: "/auth/forgot-password",
		ResetPassword: "/auth/reset-password",
		AccountVerification: "/auth/account-verification",
	},
	Catalog: "/catalog",
	SpecificCatalog: "/catalog/$catalogPath",
	Delivery: "/delivery",
	Payment: "/payment",
	Conditions: "/conditions",
	Contacts: "/contacts",
	Favorite: "/favorite",
	Basket: "/basket",
	Profile: "/profile",
	Admin: {
		Base: "/admin",
		Categories: "/admin/categories",
		CategoriesCreate: "/admin/categories/create",
		CategoriesUpdate: "/admin/categories/update/{-$categoryId}",
		Products: "/admin/products",
		ProductsCreate: "/admin/products/create",
		ProductsUpdate: "/admin/products/update",
	},
} as const;
