export const Routes = {
	Main: "/",
	Auth: {
		SignUp: "/auth/sign-up",
		SignIn: "/auth/sign-in",
		ForgotPassword: "/auth/forgot-password",
		ResetPassword: "/auth/reset-password",
		AccountVerification: "/auth/account-verification",
	},
	Catalog: "/catalog",
	SpecificCatalog: "/catalog/$catalogPath",
	Delivery: "/delivery",
	Payment: "/payment",
	Conditions: "/conditions",
	Contacts: "/contacts",
	Favorite: "/favorite",
	Cart: "/cart",
	Profile: "/profile",
	Product: "/product/$productSkuId",
	Orders: "/orders",
	SpecificOrder: "/orders/{$orderNumber}",
	Admin: {
		Base: "/admin",
		Categories: "/admin/categories",
		CategoriesCreate: "/admin/categories/create",
		CategoriesUpdate: "/admin/categories/update/{-$categoryId}",
		Products: "/admin/products",
		ProductsCreate: "/admin/products/create",
		ProductsUpdate: "/admin/products/update/{-$productId}",
		ProductsCreateSku: "/admin/products/create-sku/$productId",
		ProductsUpdateSku: "/admin/products/update-sku/{-$productSkuId}",
		Manufacturers: "/admin/manufacturers",
		ManufacturersCreate: "/admin/manufacturers/create",
		ManufacturersUpdate: "/admin/manufacturers/update/{-$manufacturerId}",
		Users: "/admin/users",
		Promocode: "/admin/promocode",
		PromocodeCreate: "/admin/promocode/create",
		PromocodeUpdate: "/admin/promocode/update/{-$promocodeId}",
	},
} as const;
